name: YueDuFlutter
description: 致力于优质的阅读体验!

# 以下定义了应用程序的版本号和内部版本号。
# 版本号是由点分隔的三个数字组成，如 1.2.43
# 后跟一个用 + 分隔的可选构建号。
# 通过分别指定 --build-name 和 --build-number ，可以在 flutter 构建中覆盖版本号和构建器号。
# 在 Android 中，build-name 用作 versionName ，而 build-number 用作 versionCode。
# 阅读更多关于Android版本的信息 https://developer.android.com/studio/publish/versioning
# 在 iOS 中， build-name 用作 CFBundleShortVersionString ，而 build-number 用作 CFBundleVersion 。
# 阅读更多关于iOS版本的信息
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 以下内容将 Cupertino Icons 字体添加到您的应用程序中。
  # 与 CupertinoIcons 类一起使用，用于iOS样式图标。
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# 有关此文件的通用Dart部分的信息，请参阅以下页面
# https://www.dartlang.org/tools/pub/pubspec

# 以下部分专门针对 Flutter
flutter:

  # 以下行确保应用程序中包含“材质图标”字体，以便您可以使用材质“图标”类中的图标。
  uses-material-design: true

  # 要向应用程序添加资源，请添加资源部分，如下所示：
  assets:
    - lib/images/
  #  - images/a_dot_ham.jpeg

  # 图像资源可以指一个或多个特定于分辨率的“变体”，请参阅
  # https://flutter.io/assets-and-images/#resolution-aware.

  # 有关从包依赖项添加资源的详细信息，请参阅
  # https://flutter.io/assets-and-images/#from-packages

  # 要在应用程序中添加自定义字体，请在此处“ flutter ”部分中添加字体部分。
  # 此列表中的每个条目都应具有带有字体系列名称的“族”键，以及带有列表的“ fonts ”键，
  # 该列表给出该字体的资产和其他描述符。 例如：
  fonts:
    - family: KTGB2312
      fonts:
        - asset: lib/fonts/KTGB2312.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 有关包依赖关系中的字体的详细信息，请参阅
  # https://flutter.io/custom-fonts/#from-packages
